general.import = ["~/.config/alacritty/rose-pine.toml"]

[window]
padding = { x = 4, y = 4 }
opacity = 1

[scrolling]
history = 10000

[font]
normal = { family = "JetBrains Mono", style = "Medium" }
bold = { family = "JetBrains Mono", style = "Bold" } 
italic = { family = "JetBrains Mono", style = "Medium Italic" } 
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" } 
size = 22 
